name: opus_caf_converter_dart
description: A powerful Dart package designed to effortlessly and losslessly convert Opus files to Apple's Core Audio Format (CAF), enabling the seamless integration of Opus audio in iOS systems
version: 1.0.1
homepage: https://github.com/nabil6391/opus_caf_converter_dart

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
